In [116]:
import sys
print(sys.executable)

c:\Users\DELL\OneDrive\Desktop\Loan Risk Analysis\zubair9141@gmail.com\Python Analysis & Web App\loan_app\credit_env1\Scripts\python.exe

In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics

In [118]:
cibil = pd.read_csv(r'C:\Users\DELL\OneDrive\Desktop\PRP Project-1\1. Data\EXTERNAL_CIBIL_DATA.csv')
bank = pd.read_csv(r'C:\Users\DELL\OneDrive\Desktop\PRP Project-1\1. Data\INTERNAL_BANK_DATA.csv')

In [119]:
cibil.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [120]:
for i in cibil.columns:
    print(cibil[i].value_counts())
    print('\n')

PROSPECTID
1        1
2        1
3        1
4        1
5        1
        ..
51332    1
51333    1
51334    1
51335    1
51336    1
Name: count, Length: 51336, dtype: int64


time_since_recent_payment
-99999    4291
 51        606
 49        605
 63        604
 52        580
          ...
 1541        1
 963         1
 1621        1
 2382        1
 2383        1
Name: count, Length: 2435, dtype: int64


time_since_first_deliquency
-99999    35949
 35        1855
 34         596
 33         563
 7          488
 9          475
 29         471
 31         468
 6          467
 5          466
 8          459
 10         454
 32         447
 30         446
 11         441
 27         435
 26         431
 28         429
 12         412
 4          402
 14         396
 13         393
 25         392
 18         372
 3          366
 17         362
 15         356
 16         351
 24         349
 19         317
 21         313
 22         306
 20         293
 23         267
 2          240
 1           81
 0           28
Name: count, dtype: int64


time_since_recent_deliquency
-99999    35949
 2         1224
 3         1091
 4         1016
 5          853
 6          792
 7          649
 8          642
 9          593
 10         516
 1          515
 11         454
 20         443
 13         432
 14         408
 12         385
 19         359
 21         352
 24         326
 22         326
 26         326
 25         323
 15         321
 17         318
 16         311
 23         297
 18         287
 27         270
 28         238
 29         232
 31         197
 30         194
 33         170
 32         164
 34         151
 35         129
 0           83
Name: count, dtype: int64


num_times_delinquent
0     35949
1      4397
2      2533
3      1745
4      1191
      ...
67        1
53        1
51        1
46        1
74        1
Name: count, Length: 64, dtype: int64


max_delinquency_level
-99999    35949
 30         733
 26         731
 28         603
 25         584
          ...
 633          1
 585          1
 756          1
 337          1
 557          1
Name: count, Length: 519, dtype: int64


max_recent_level_of_deliq
0      35949
30      1241
25       993
26       935
28       828
       ...
750        1
191        1
670        1
184        1
468        1
Name: count, Length: 399, dtype: int64


num_deliq_6mts
0     46554
1      2453
2      1096
3       534
4       434
5       168
6        56
7        16
8        13
10        5
9         4
12        2
11        1
Name: count, dtype: int64


num_deliq_12mts
0     42908
1      3350
2      1770
3      1040
4       614
5       462
6       340
7       232
8       186
10      147
9       127
11       61
12       36
13       16
14       14
15        8
16        6
17        4
18        4
20        3
19        2
22        2
21        1
24        1
25        1
28        1
Name: count, dtype: int64


num_deliq_6_12mts
0     45187
1      2584
2      1388
3       791
4       516
6       379
5       322
7        63
8        39
9        21
10       19
11       11
12        9
13        3
14        1
20        1
16        1
17        1
Name: count, dtype: int64


max_deliq_6mts
 0        33664
-99999    12890
 28         324
 3          323
 26         298
          ...
 202          1
 606          1
 810          1
 337          1
 181          1
Name: count, Length: 206, dtype: int64


max_deliq_12mts
 0        32076
-99999    10832
 28         564
 26         503
 27         438
          ...
 102          1
 281          1
 337          1
 363          1
 95           1
Name: count, Length: 294, dtype: int64


num_times_30p_dpd
0     43345
1      2471
2      1503
3       876
4       574
5       438
6       355
7       247
8       232
9       193
10      171
11      135
12      118
13      114
15       94
14       80
16       74
17       51
19       35
18       32
21       27
20       20
24       16
23       16
22       16
26       13
27       12
34       10
25        9
28        9
33        6
35        6
29        5
36        4
37        4
30        3
32        3
31        3
44        2
46        2
43        1
51        1
48        1
54        1
53        1
38        1
56        1
39        1
60        1
58        1
59        1
47        1
Name: count, dtype: int64


num_times_60p_dpd
0     46447
1      1703
2       839
3       478
4       367
5       257
6       204
8       152
7       148
11       99
10       96
9        94
12       77
13       70
14       47
15       44
17       32
16       31
21       18
18       17
23       16
19       13
22       11
20        9
27        7
25        7
32        6
24        6
28        6
34        6
35        5
33        4
30        4
31        4
26        3
29        2
37        1
45        1
48        1
36        1
49        1
52        1
41        1
Name: count, dtype: int64


num_std
0      31655
1       1450
2       1036
3        948
4        751
       ...
327        1
212        1
201        1
273        1
331        1
Name: count, Length: 237, dtype: int64


num_std_6mts
0     37369
4      3529
5      2640
1      1378
3      1346
2      1273
8       669
10      546
6       534
7       422
9       343
12      233
11      205
15      147
13      114
14       97
16       97
18       52
17       49
19       44
20       40
25       27
22       22
21       22
23       20
24       16
30       16
27       13
26       13
29        7
31        6
32        6
33        5
38        5
28        4
37        4
35        3
34        3
40        3
36        2
42        2
52        2
44        1
39        1
58        1
60        1
45        1
43        1
41        1
49        1
Name: count, dtype: int64


num_std_12mts
0      35636
10      1958
11      1624
1       1324
2       1022
       ...
88         1
100        1
77         1
102        1
90         1
Name: count, Length: 98, dtype: int64


num_sub
0     50682
1       179
2       101
3        65
4        51
5        43
6        43
7        32
8        32
10       22
11       21
9        18
12        8
13        7
14        6
19        4
21        4
20        3
15        2
16        2
17        1
41        1
25        1
42        1
23        1
26        1
27        1
30        1
24        1
22        1
40        1
Name: count, dtype: int64


num_sub_6mts
0    51285
1       18
2       14
4        7
3        6
5        5
8        1
Name: count, dtype: int64


num_sub_12mts
0     51178
1        61
2        42
3        14
6        11
5         9
4         6
10        5
11        3
8         3
9         1
20        1
12        1
7         1
Name: count, dtype: int64


num_dbt
0     51166
1        45
3        15
2        12
5        12
6        11
9        10
7         8
8         7
11        6
13        5
25        4
10        4
14        4
24        3
22        3
26        3
12        2
17        2
15        2
16        2
18        2
19        2
23        1
4         1
31        1
32        1
35        1
28        1
Name: count, dtype: int64


num_dbt_6mts
0    51320
4        8
3        4
5        2
2        1
6        1
Name: count, dtype: int64


num_dbt_12mts
0     51296
2        11
10        6
9         5
3         4
1         4
4         3
5         3
11        2
8         1
12        1
Name: count, dtype: int64


num_lss
0     51234
1        21
3        11
7        10
4         9
2         8
8         7
16        5
9         5
6         4
5         3
10        3
19        2
15        2
11        2
72        1
17        1
34        1
12        1
21        1
25        1
31        1
14        1
20        1
13        1
Name: count, dtype: int64


num_lss_6mts
0     51324
4         5
5         2
2         2
3         1
12        1
1         1
Name: count, dtype: int64


num_lss_12mts
0     51311
1         5
2         5
10        4
5         3
3         2
8         2
30        1
9         1
11        1
4         1
Name: count, dtype: int64


recent_level_of_deliq
0      35949
30      1101
25      1017
26       929
28       777
       ...
750        1
670        1
299        1
184        1
468        1
Name: count, Length: 349, dtype: int64


tot_enq
 1        9476
 2        7802
-99999    6321
 3        6087
 4        4626
          ...
 65          1
 94          1
 67          1
 69          1
 86          1
Name: count, Length: 85, dtype: int64


CC_enq
 0        37180
-99999     6321
 1         3983
 2         1499
 3          737
 4          451
 5          283
 6          199
 7          152
 8          124
 9           70
 10          69
 11          60
 12          48
 14          32
 13          30
 16          18
 15          16
 17           9
 19           9
 18           8
 24           7
 20           6
 22           4
 21           3
 23           3
 25           2
 26           2
 30           2
 42           1
 28           1
 29           1
 34           1
 39           1
 35           1
 33           1
 36           1
 37           1
Name: count, dtype: int64


CC_enq_L6m
 0        41080
-99999     6321
 1         2389
 2          811
 3          337
 4          187
 5           75
 6           58
 7           38
 8           13
 9           10
 11           5
 10           4
 12           4
 13           2
 17           1
 14           1
Name: count, dtype: int64


CC_enq_L12m
 0        39563
-99999     6321
 1         3074
 2         1042
 3          491
 4          291
 5          176
 6          119
 7           82
 8           55
 9           40
 10          28
 11          20
 12          11
 13           7
 14           7
 15           3
 17           2
 20           1
 24           1
 16           1
 19           1
Name: count, dtype: int64


PL_enq
 0        26084
 1         8373
-99999     6321
 2         4316
 3         2223
 4         1311
 5          746
 6          527
 7          383
 8          245
 9          187
 10         129
 11          98
 12          80
 14          55
 13          54
 15          44
 17          27
 18          19
 19          15
 20          15
 22          12
 16          12
 21           9
 24           8
 26           8
 23           5
 28           4
 25           4
 31           3
 32           3
 29           2
 43           2
 36           2
 27           2
 30           2
 37           1
 35           1
 46           1
 33           1
 44           1
 34           1
Name: count, dtype: int64


PL_enq_L6m
 0        33915
-99999     6321
 1         6228
 2         2479
 3         1024
 4          491
 5          277
 6          201
 7          116
 8           75
 9           58
 10          33
 11          27
 12          20
 13          14
 14          14
 15          12
 17           8
 16           5
 18           4
 20           2
 22           2
 19           2
 26           2
 28           1
 27           1
 44           1
 24           1
 21           1
 32           1
Name: count, dtype: int64


PL_enq_L12m
 0        29953
 1         7850
-99999     6321
 2         3382
 3         1592
 4          773
 5          438
 6          267
 7          234
 8          133
 9           87
 10          66
 11          54
 12          36
 13          30
 14          24
 15          23
 18          14
 17          12
 16           8
 19           7
 26           5
 23           4
 21           4
 22           3
 20           3
 44           2
 29           2
 27           1
 40           1
 36           1
 31           1
 30           1
 32           1
 38           1
 28           1
 33           1
Name: count, dtype: int64


time_since_recent_enq
-99999    6321
 1        2350
 2        2298
 3        1781
 4        1339
          ...
 2905        1
 2138        1
 2340        1
 2461        1
 3263        1
Name: count, Length: 2382, dtype: int64


enq_L12m
 1        11200
 0         9373
 2         7284
-99999     6321
 3         4898
          ...
 52           1
 54           1
 68           1
 58           1
 55           1
Name: count, Length: 66, dtype: int64


enq_L6m
 0        15669
 1        11377
 2         6478
-99999     6321
 3         3805
 4         2394
 5         1483
 6          994
 7          684
 8          492
 9          353
 10         242
 11         215
 12         158
 13         120
 14          83
 15          76
 17          64
 16          56
 18          50
 19          37
 20          25
 21          23
 23          18
 26          17
 24          14
 22          12
 30           8
 27           7
 25           6
 38           5
 28           5
 29           4
 36           4
 32           4
 34           4
 31           4
 33           4
 35           3
 43           2
 41           2
 60           1
 40           1
 42           1
 39           1
 48           1
 37           1
 54           1
 51           1
 53           1
 66           1
 52           1
 45           1
 50           1
 46           1
Name: count, dtype: int64


enq_L3m
 0        21116
 1        11525
-99999     6321
 2         5516
 3         2865
 4         1556
 5          799
 6          494
 7          317
 8          232
 9          154
 10         120
 11          69
 12          53
 13          45
 14          31
 15          21
 16          20
 17          14
 20          11
 18          11
 19           8
 23           6
 29           4
 21           4
 26           4
 24           3
 31           3
 28           2
 22           2
 27           2
 37           2
 32           1
 25           1
 35           1
 36           1
 38           1
 42           1
Name: count, dtype: int64


MARITALSTATUS
Married    37752
Single     13584
Name: count, dtype: int64


EDUCATION
GRADUATE          16673
12TH              14467
SSC                9276
UNDER GRADUATE     5492
OTHERS             2917
POST-GRADUATE      2242
PROFESSIONAL        269
Name: count, dtype: int64


AGE
28    2534
29    2531
27    2517
26    2450
30    2435
25    2388
24    2332
32    2297
31    2294
33    2105
34    2057
23    2049
35    1851
36    1805
22    1701
38    1594
37    1475
39    1289
40    1238
41    1165
42    1130
21    1128
43    1120
44    1012
46     851
45     827
47     668
48     647
49     616
50     529
51     431
52     380
53     359
54     300
55     275
56     212
58     180
57     162
59     146
60      99
61      59
62      41
64      26
63      25
65       3
67       2
77       1
Name: count, dtype: int64


GENDER
M    45245
F     6091
Name: count, dtype: int64


NETMONTHLYINCOME
25000    4904
20000    4880
30000    3940
15000    3669
18000    2966
         ...
29530       1
31900       1
11685       1
28470       1
12802       1
Name: count, Length: 1316, dtype: int64


Time_With_Curr_Empr
66     1574
125    1552
126    1301
71      906
62      813
       ...
456       1
441       1
337       1
413       1
661       1
Name: count, Length: 490, dtype: int64


pct_of_active_TLs_ever
1.000    18377
0.000     8519
0.500     5844
0.667     2599
0.333     2405
         ...
0.483        1
0.564        1
0.762        1
0.210        1
0.106        1
Name: count, Length: 421, dtype: int64


pct_opened_TLs_L6m_of_L12m
0.000    30574
1.000    10210
0.500     4185
0.667     1411
0.333     1349
         ...
0.176        1
0.071        1
0.812        1
0.469        1
0.688        1
Name: count, Length: 109, dtype: int64


pct_currentBal_all_TL
0.000     11819
1.000      2460
0.500       460
0.667       248
0.600       236
          ...
4.593         1
1.349         1
1.328         1
1.510         1
70.675        1
Name: count, Length: 1529, dtype: int64


CC_utilization
-99999.000    47636
 1.000          597
 0.000          572
 0.001           18
 0.991           16
              ...
 0.017            1
 0.777            1
 0.084            1
 0.092            1
 71.059           1
Name: count, Length: 907, dtype: int64


CC_Flag
0    46743
1     4593
Name: count, dtype: int64


PL_utilization
-99999.000    44435
 1.000          646
 0.000          178
 0.949           60
 0.931           56
              ...
 0.139            1
 0.502            1
 1.121            1
 0.051            1
 0.209            1
Name: count, Length: 918, dtype: int64


PL_Flag
0    42718
1     8618
Name: count, dtype: int64


pct_PL_enq_L6m_of_L12m
0.000    40236
1.000     8126
0.500     1036
0.667      463
0.333      326
         ...
0.970        1
0.083        1
0.364        1
0.304        1
0.421        1
Name: count, Length: 93, dtype: int64


pct_CC_enq_L6m_of_L12m
0.000    47401
1.000     2688
0.500      436
0.667      193
0.333      132
0.750       77
0.250       57
0.600       49
0.800       39
0.400       36
0.200       26
0.833       21
0.429       20
0.714       17
0.571       16
0.857       11
0.375        9
0.700        8
0.778        7
0.875        7
0.286        7
0.444        7
0.167        6
0.222        6
0.625        5
0.300        5
0.364        4
0.545        4
0.143        3
0.125        3
0.455        3
0.556        3
0.692        2
0.583        2
0.100        2
0.273        2
0.818        2
0.889        2
0.462        2
0.636        2
0.091        1
0.850        1
0.917        1
0.643        1
0.294        1
0.688        1
0.538        1
0.706        1
0.900        1
0.727        1
0.786        1
0.867        1
0.923        1
0.579        1
Name: count, dtype: int64


pct_PL_enq_L6m_of_ever
0.000    40236
1.000     6591
0.500     1407
0.333      594
0.667      510
         ...
0.656        1
0.867        1
0.269        1
0.235        1
0.842        1
Name: count, Length: 141, dtype: int64


pct_CC_enq_L6m_of_ever
0.000    47401
1.000     2095
0.500      543
0.333      248
0.667      167
         ...
0.688        1
0.867        1
0.050        1
0.357        1
0.040        1
Name: count, Length: 93, dtype: int64


max_unsec_exposure_inPct
-99999.000    23178
 0.000          581
 0.001          145
 1.000          144
 5.000          121
              ...
 19.639           1
 22.652           1
 6.107            1
 3.875            1
 6.763            1
Name: count, Length: 8975, dtype: int64


HL_Flag
0    37418
1    13918
Name: count, dtype: int64


GL_Flag
0    48621
1     2715
Name: count, dtype: int64


last_prod_enq2
others          20831
ConsumerLoan    17793
PL               7959
CC               2339
AL               1511
HL                903
Name: count, dtype: int64


first_prod_enq2
others          28120
ConsumerLoan    11860
PL               4889
AL               2870
CC               2188
HL               1409
Name: count, dtype: int64


Credit_Score
682    1357
678    1340
679    1330
680    1321
677    1259
       ...
499       1
489       1
801       1
469       1
513       1
Name: count, Length: 250, dtype: int64


Approved_Flag
P2    32199
P3     7452
P4     5882
P1     5803
Name: count, dtype: int64

In [121]:
cibil.info()

<class 'pandas.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  str
 39  EDUCATION                     51336 non-null  str
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  str
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  str
 59  first_prod_enq2               51336 non-null  str
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  str
dtypes: float64(10), int64(46), str(6)
memory usage: 25.8 MB

In [122]:
cibil.replace(-99999, np.nan, inplace = True)

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549.0,35.0,15.0,11,29.0,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302.0,11.0,3.0,9,25.0,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,NaN,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15.0,24.0,23.0,2,24.0,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,others,others,681,P2

In [123]:
cibil.columns

Index(['PROSPECTID', 'time_since_recent_payment',
       'time_since_first_deliquency', 'time_since_recent_deliquency',
       'num_times_delinquent', 'max_delinquency_level',
       'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts',
       'num_deliq_6_12mts', 'max_deliq_6mts', 'max_deliq_12mts',
       'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std', 'num_std_6mts',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_6mts', 'num_dbt_12mts', 'num_lss', 'num_lss_6mts',
       'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq',
       'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m',
       'time_since_recent_enq', 'enq_L12m', 'enq_L6m', 'enq_L3m',
       'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'last_prod_enq2', 'first_prod_enq2', 'Credit_Score',
       'Approved_Flag'],
      dtype='str')

In [124]:
cibil.info()

<class 'pandas.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     47045 non-null  float64
 2   time_since_first_deliquency   15387 non-null  float64
 3   time_since_recent_deliquency  15387 non-null  float64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         15387 non-null  float64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                38446 non-null  float64
 11  max_deliq_12mts               40504 non-null  float64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       45015 non-null  float64
 28  CC_enq                        45015 non-null  float64
 29  CC_enq_L6m                    45015 non-null  float64
 30  CC_enq_L12m                   45015 non-null  float64
 31  PL_enq                        45015 non-null  float64
 32  PL_enq_L6m                    45015 non-null  float64
 33  PL_enq_L12m                   45015 non-null  float64
 34  time_since_recent_enq         45015 non-null  float64
 35  enq_L12m                      45015 non-null  float64
 36  enq_L6m                       45015 non-null  float64
 37  enq_L3m                       45015 non-null  float64
 38  MARITALSTATUS                 51336 non-null  str
 39  EDUCATION                     51336 non-null  str
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  str
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51264 non-null  float64
 47  CC_utilization                3700 non-null   float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                6901 non-null   float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      28158 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  str
 59  first_prod_enq2               51336 non-null  str
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  str
dtypes: float64(27), int64(29), str(6)
memory usage: 25.8 MB

In [125]:
cat_cols = cibil.select_dtypes(include = 'object')
num_cols = cibil.select_dtypes(exclude = 'object')

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\3929470138.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = cibil.select_dtypes(include = 'object')

In [126]:
((num_cols.isnull().sum()/len(num_cols))*100).sort_values(ascending = False)

CC_utilization                  92.792582
PL_utilization                  86.557192
time_since_recent_deliquency    70.026882
time_since_first_deliquency     70.026882
max_delinquency_level           70.026882
max_unsec_exposure_inPct        45.149603
max_deliq_6mts                  25.109085
max_deliq_12mts                 21.100203
CC_enq                          12.312997
CC_enq_L6m                      12.312997
time_since_recent_enq           12.312997
PL_enq_L12m                     12.312997
PL_enq_L6m                      12.312997
enq_L12m                        12.312997
enq_L3m                         12.312997
enq_L6m                         12.312997
tot_enq                         12.312997
PL_enq                          12.312997
CC_enq_L12m                     12.312997
time_since_recent_payment        8.358657
pct_currentBal_all_TL            0.140252
num_deliq_6mts                   0.000000
PROSPECTID                       0.000000
num_times_delinquent             0.000000
num_lss                          0.000000
num_dbt_12mts                    0.000000
num_dbt_6mts                     0.000000
num_dbt                          0.000000
num_sub_12mts                    0.000000
num_sub_6mts                     0.000000
num_sub                          0.000000
num_std_12mts                    0.000000
num_std_6mts                     0.000000
num_std                          0.000000
num_times_60p_dpd                0.000000
num_times_30p_dpd                0.000000
num_deliq_12mts                  0.000000
num_deliq_6_12mts                0.000000
max_recent_level_of_deliq        0.000000
recent_level_of_deliq            0.000000
NETMONTHLYINCOME                 0.000000
AGE                              0.000000
num_lss_6mts                     0.000000
num_lss_12mts                    0.000000
pct_opened_TLs_L6m_of_L12m       0.000000
pct_of_active_TLs_ever           0.000000
CC_Flag                          0.000000
Time_With_Curr_Empr              0.000000
PL_Flag                          0.000000
pct_PL_enq_L6m_of_L12m           0.000000
pct_PL_enq_L6m_of_ever           0.000000
pct_CC_enq_L6m_of_L12m           0.000000
pct_CC_enq_L6m_of_ever           0.000000
HL_Flag                          0.000000
GL_Flag                          0.000000
Credit_Score                     0.000000
dtype: float64

In [127]:
cibil[['CC_utilization',
       'PL_utilization',
       'time_since_recent_deliquency',
       'time_since_first_deliquency',
       'max_delinquency_level',
       'max_unsec_exposure_inPct',
       'max_deliq_6mts',
       'max_deliq_12mts',
       'CC_enq',
       'CC_enq_L6m',
       'time_since_recent_enq',
       'PL_enq_L12m',
       'PL_enq_L6m',
       'enq_L12m',
       'enq_L3m',
       'enq_L6m',
       'tot_enq',
       'PL_enq',
       'CC_enq_L12m',
       'time_since_recent_payment',
       'pct_currentBal_all_TL'
]].head()

,CC_utilization,PL_utilization,time_since_recent_deliquency,time_since_first_deliquency,max_delinquency_level,max_unsec_exposure_inPct,max_deliq_6mts,max_deliq_12mts,CC_enq,CC_enq_L6m,...,PL_enq_L12m,PL_enq_L6m,enq_L12m,enq_L3m,enq_L6m,tot_enq,PL_enq,CC_enq_L12m,time_since_recent_payment,pct_currentBal_all_TL
0,NaN,0.798,15.0,35.0,29.0,13.333,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,549.0,0.798
1,NaN,NaN,NaN,NaN,NaN,0.860,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,47.0,0.370
2,NaN,NaN,3.0,11.0,25.0,5741.667,25.0,25.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,302.0,0.585
3,NaN,NaN,NaN,NaN,NaN,9.900,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.990
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,583.0,0.000

1. Utilization Columns (VERY HIGH missing)

90% missing = almost useless
Imputation will introduce noise

In [128]:
cibil.drop(columns = ['CC_utilization','PL_utilization'], inplace = True)

CC_utilization                  92.792582
PL_utilization                  86.557192
time_since_recent_deliquency    70.026882
time_since_first_deliquency     70.026882
max_delinquency_level           70.026882
max_unsec_exposure_inPct        45.149603
max_deliq_6mts                  25.109085
max_deliq_12mts                 21.100203
CC_enq                          12.312997
CC_enq_L6m                      12.312997
time_since_recent_enq           12.312997
PL_enq_L12m                     12.312997
PL_enq_L6m                      12.312997
enq_L12m                        12.312997
enq_L3m                         12.312997
enq_L6m                         12.312997
tot_enq                         12.312997
PL_enq                          12.312997
CC_enq_L12m                     12.312997

2. Time Since Delinquency (VERY IMPORTANT)

In [129]:
cibil['time_since_recent_deliquency'] = cibil['time_since_recent_deliquency'].fillna(0)
cibil['time_since_first_deliquency'] = cibil['time_since_first_deliquency'].fillna(0)
cibil['max_delinquency_level'] = cibil['max_delinquency_level'].fillna(0)

3. Delinquency Severity

In [130]:
# Missing = no delinquency
# 0 = safe default
cibil['max_delinquency_level'] = cibil['max_delinquency_level'].fillna(0)
cibil['max_deliq_6mts'] = cibil['max_deliq_6mts'].fillna(0)
cibil['max_deliq_12mts'] = cibil['max_deliq_12mts'].fillna(0)

4. Exposure (continuous, risky feature)

In [131]:
cibil['max_unsec_exposure_inPct'] = cibil['max_unsec_exposure_inPct'].fillna(cibil['max_unsec_exposure_inPct'].median())

5. Enquiry Columns (~12% missing)

In [132]:
enquiry_cols = [
    'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m',
    'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m',
    'enq_L12m', 'enq_L6m', 'enq_L3m',
    'tot_enq', 'time_since_recent_enq'
]

cibil[enquiry_cols] = cibil[enquiry_cols].fillna(0)

6. Payment Time

In [133]:
cibil['time_since_recent_payment'] = cibil['time_since_recent_payment'].fillna(cibil['time_since_recent_payment'].median())

7. Low missing

In [134]:
cibil['pct_currentBal_all_TL'] = cibil['pct_currentBal_all_TL'].fillna(cibil['pct_currentBal_all_TL'].median())

In [135]:
((cibil.isnull().sum()/len(cibil))*100).sort_values(ascending = True)

PROSPECTID                      0.0
time_since_recent_payment       0.0
time_since_first_deliquency     0.0
time_since_recent_deliquency    0.0
num_times_delinquent            0.0
max_delinquency_level           0.0
max_recent_level_of_deliq       0.0
num_deliq_6mts                  0.0
num_deliq_12mts                 0.0
num_deliq_6_12mts               0.0
max_deliq_6mts                  0.0
max_deliq_12mts                 0.0
num_times_30p_dpd               0.0
num_times_60p_dpd               0.0
num_std                         0.0
num_std_6mts                    0.0
num_std_12mts                   0.0
num_sub                         0.0
num_sub_6mts                    0.0
num_sub_12mts                   0.0
num_dbt                         0.0
num_dbt_6mts                    0.0
num_dbt_12mts                   0.0
num_lss                         0.0
num_lss_6mts                    0.0
num_lss_12mts                   0.0
recent_level_of_deliq           0.0
tot_enq                         0.0
CC_enq                          0.0
CC_enq_L6m                      0.0
CC_enq_L12m                     0.0
PL_enq                          0.0
PL_enq_L6m                      0.0
PL_enq_L12m                     0.0
time_since_recent_enq           0.0
enq_L12m                        0.0
enq_L6m                         0.0
enq_L3m                         0.0
MARITALSTATUS                   0.0
EDUCATION                       0.0
AGE                             0.0
GENDER                          0.0
NETMONTHLYINCOME                0.0
Time_With_Curr_Empr             0.0
pct_of_active_TLs_ever          0.0
pct_opened_TLs_L6m_of_L12m      0.0
pct_currentBal_all_TL           0.0
CC_Flag                         0.0
PL_Flag                         0.0
pct_PL_enq_L6m_of_L12m          0.0
pct_CC_enq_L6m_of_L12m          0.0
pct_PL_enq_L6m_of_ever          0.0
pct_CC_enq_L6m_of_ever          0.0
max_unsec_exposure_inPct        0.0
HL_Flag                         0.0
GL_Flag                         0.0
last_prod_enq2                  0.0
first_prod_enq2                 0.0
Credit_Score                    0.0
Approved_Flag                   0.0
dtype: float64

In [136]:
df = pd.merge(cibil, bank, on='PROSPECTID', how='inner')

In [137]:
cat_col = df.select_dtypes(include = 'object')
num_col = df.select_dtypes(exclude = 'object')

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\477469805.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df.select_dtypes(include = 'object')

In [138]:
((num_col.isnull().sum()/len(num_col))*100).sort_values(ascending = True)

PROSPECTID                      0.0
time_since_recent_payment       0.0
time_since_first_deliquency     0.0
time_since_recent_deliquency    0.0
num_times_delinquent            0.0
                               ...
Secured_TL                      0.0
Unsecured_TL                    0.0
Other_TL                        0.0
Age_Oldest_TL                   0.0
Age_Newest_TL                   0.0
Length: 79, dtype: float64

for i in num_col:
    sns.boxplot(data = df, x = i)
    plt.show()

In [139]:
df.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,549.0,35.0,15.0,11,29.0,29,0,0,0,...,0,0,1,0,4,1,4,0,72,18
1,2,47.0,0.0,0.0,0,0.0,0,0,0,0,...,0,1,0,0,0,0,1,0,7,7
2,3,302.0,11.0,3.0,9,25.0,25,1,9,8,...,0,6,1,0,0,2,6,0,47,2
3,4,74.0,0.0,0.0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,1,1,5,5
4,5,583.0,0.0,0.0,0,0.0,0,0,0,0,...,0,0,0,0,0,3,0,2,131,32

In [140]:
df.drop(columns = ['PROSPECTID'], inplace = True)

In [141]:
df.columns

Index(['time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever',
       'max_unsec_exposure_inPct', 'HL_Flag', 'GL_Flag', 'last_prod_enq2',
       'first_prod_enq2', 'Credit_Score', 'Approved_Flag', 'Total_TL',
       'Tot_Closed_TL', 'Tot_Active_TL', 'Total_TL_opened_L6M',
       'Tot_TL_closed_L6M', 'pct_tl_open_L6M', 'pct_tl_closed_L6M',
       'pct_active_tl', 'pct_closed_tl', 'Total_TL_opened_L12M',
       'Tot_TL_closed_L12M', 'pct_tl_open_L12M', 'pct_tl_closed_L12M',
       'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL', 'Consumer_TL', 'Gold_TL',
       'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL',
       'Age_Oldest_TL', 'Age_Newest_TL'],
      dtype='str')

In [142]:
cat_col.head()

,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,Married,12TH,M,PL,PL,P2
1,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,Married,SSC,M,ConsumerLoan,others,P2
3,Married,SSC,M,others,others,P2
4,Married,POST-GRADUATE,M,AL,AL,P1

In [143]:
for i in cat_col.columns:
    print(cat_col[i].value_counts())
    print('\n')

MARITALSTATUS
Married    37752
Single     13584
Name: count, dtype: int64


EDUCATION
GRADUATE          16673
12TH              14467
SSC                9276
UNDER GRADUATE     5492
OTHERS             2917
POST-GRADUATE      2242
PROFESSIONAL        269
Name: count, dtype: int64


GENDER
M    45245
F     6091
Name: count, dtype: int64


last_prod_enq2
others          20831
ConsumerLoan    17793
PL               7959
CC               2339
AL               1511
HL                903
Name: count, dtype: int64


first_prod_enq2
others          28120
ConsumerLoan    11860
PL               4889
AL               2870
CC               2188
HL               1409
Name: count, dtype: int64


Approved_Flag
P2    32199
P3     7452
P4     5882
P1     5803
Name: count, dtype: int64

In [144]:
# Encoding

In [145]:
df['GENDER'] = df['GENDER'].map({'M': 1, 'F': 0})

In [146]:
education_map = {
    'OTHERS': 0,
    'SSC': 1,
    '12TH': 2,
    'UNDER GRADUATE': 3,
    'GRADUATE': 4,
    'POST-GRADUATE': 5,
    'PROFESSIONAL': 6
}

df['EDUCATION'] = df['EDUCATION'].map(education_map)

In [147]:
df = pd.get_dummies(df, columns=[
    'MARITALSTATUS',
    'last_prod_enq2',
    'first_prod_enq2'
], drop_first=True)

In [148]:
df['Approved_Flag'] = df['Approved_Flag'].map({'P1': 0,'P2': 0,'P3': 1,'P4': 1})

In [149]:
df.columns

Index(['time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever',
       'max_unsec_exposure_inPct', 'HL_Flag', 'GL_Flag', 'Credit_Score',
       'Approved_Flag', 'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'MARITALSTATUS_Single', 'last_prod_enq2_CC',
       'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL',
       'last_prod_enq2_others', 'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL',
       'first_prod_enq2_PL', 'first_prod_enq2_others'],
      dtype='str')

In [150]:
df.Approved_Flag

0        0
1        0
2        0
3        0
4        0
        ..
51331    1
51332    0
51333    1
51334    0
51335    0
Name: Approved_Flag, Length: 51336, dtype: int64

In [151]:
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [152]:
def vif_cal(Z):
    x_var = Z.copy()
    xvar_names = x_var.columns
    
    for i in range(len(xvar_names)):
        y_col = xvar_names[i]
        x_cols = xvar_names.drop(y_col)
        
        # build formula correctly
        formula = f"{y_col} ~ " + " + ".join(x_cols)
        
        model = smf.ols(formula=formula, data=x_var).fit()
        rsq = model.rsquared
        
        vif = round(1 / (1 - rsq), 2)
        print(y_col, "VIF =", vif)

In [153]:
y = df.Approved_Flag
df.drop('Approved_Flag', axis = 1, inplace = True)

In [154]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 91 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   time_since_recent_payment     51336 non-null  float64
 1   time_since_first_deliquency   51336 non-null  float64
 2   time_since_recent_deliquency  51336 non-null  float64
 3   num_times_delinquent          51336 non-null  int64
 4   max_delinquency_level         51336 non-null  float64
 5   max_recent_level_of_deliq     51336 non-null  int64
 6   num_deliq_6mts                51336 non-null  int64
 7   num_deliq_12mts               51336 non-null  int64
 8   num_deliq_6_12mts             51336 non-null  int64
 9   max_deliq_6mts                51336 non-null  float64
 10  max_deliq_12mts               51336 non-null  float64
 11  num_times_30p_dpd             51336 non-null  int64
 12  num_times_60p_dpd             51336 non-null  int64
 13  num_std                       51336 non-null  int64
 14  num_std_6mts                  51336 non-null  int64
 15  num_std_12mts                 51336 non-null  int64
 16  num_sub                       51336 non-null  int64
 17  num_sub_6mts                  51336 non-null  int64
 18  num_sub_12mts                 51336 non-null  int64
 19  num_dbt                       51336 non-null  int64
 20  num_dbt_6mts                  51336 non-null  int64
 21  num_dbt_12mts                 51336 non-null  int64
 22  num_lss                       51336 non-null  int64
 23  num_lss_6mts                  51336 non-null  int64
 24  num_lss_12mts                 51336 non-null  int64
 25  recent_level_of_deliq         51336 non-null  int64
 26  tot_enq                       51336 non-null  float64
 27  CC_enq                        51336 non-null  float64
 28  CC_enq_L6m                    51336 non-null  float64
 29  CC_enq_L12m                   51336 non-null  float64
 30  PL_enq                        51336 non-null  float64
 31  PL_enq_L6m                    51336 non-null  float64
 32  PL_enq_L12m                   51336 non-null  float64
 33  time_since_recent_enq         51336 non-null  float64
 34  enq_L12m                      51336 non-null  float64
 35  enq_L6m                       51336 non-null  float64
 36  enq_L3m                       51336 non-null  float64
 37  EDUCATION                     51336 non-null  int64
 38  AGE                           51336 non-null  int64
 39  GENDER                        51336 non-null  int64
 40  NETMONTHLYINCOME              51336 non-null  int64
 41  Time_With_Curr_Empr           51336 non-null  int64
 42  pct_of_active_TLs_ever        51336 non-null  float64
 43  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 44  pct_currentBal_all_TL         51336 non-null  float64
 45  CC_Flag                       51336 non-null  int64
 46  PL_Flag                       51336 non-null  int64
 47  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 48  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 49  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 50  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 51  max_unsec_exposure_inPct      51336 non-null  float64
 52  HL_Flag                       51336 non-null  int64
 53  GL_Flag                       51336 non-null  int64
 54  Credit_Score                  51336 non-null  int64
 55  Total_TL                      51336 non-null  int64
 56  Tot_Closed_TL                 51336 non-null  int64
 57  Tot_Active_TL                 51336 non-null  int64
 58  Total_TL_opened_L6M           51336 non-null  int64
 59  Tot_TL_closed_L6M             51336 non-null  int64
 60  pct_tl_open_L6M               51336 non-null  float64
 61  pct_tl_closed_L6M             51336 non-null  float64
 62  pct_active_tl                 51336 non-null  float64
 63  pct_closed_tl                 51336 non-null  float64
 64  Total_TL_opened_L12M          51336 non-null  int64
 65  Tot_TL_closed_L12M            51336 non-null  int64
 66  pct_tl_open_L12M              51336 non-null  float64
 67  pct_tl_closed_L12M            51336 non-null  float64
 68  Tot_Missed_Pmnt               51336 non-null  int64
 69  Auto_TL                       51336 non-null  int64
 70  CC_TL                         51336 non-null  int64
 71  Consumer_TL                   51336 non-null  int64
 72  Gold_TL                       51336 non-null  int64
 73  Home_TL                       51336 non-null  int64
 74  PL_TL                         51336 non-null  int64
 75  Secured_TL                    51336 non-null  int64
 76  Unsecured_TL                  51336 non-null  int64
 77  Other_TL                      51336 non-null  int64
 78  Age_Oldest_TL                 51336 non-null  int64
 79  Age_Newest_TL                 51336 non-null  int64
 80  MARITALSTATUS_Single          51336 non-null  bool
 81  last_prod_enq2_CC             51336 non-null  bool
 82  last_prod_enq2_ConsumerLoan   51336 non-null  bool
 83  last_prod_enq2_HL             51336 non-null  bool
 84  last_prod_enq2_PL             51336 non-null  bool
 85  last_prod_enq2_others         51336 non-null  bool
 86  first_prod_enq2_CC            51336 non-null  bool
 87  first_prod_enq2_ConsumerLoan  51336 non-null  bool
 88  first_prod_enq2_HL            51336 non-null  bool
 89  first_prod_enq2_PL            51336 non-null  bool
 90  first_prod_enq2_others        51336 non-null  bool
dtypes: bool(11), float64(31), int64(49)
memory usage: 31.9 MB

In [155]:
bool_cols = df.select_dtypes(include=['bool']).columns

df[bool_cols] = df[bool_cols].astype(int)

In [156]:
vif_cal(Z = df[['time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever',
       'max_unsec_exposure_inPct', 'HL_Flag', 'GL_Flag', 'Credit_Score',
        'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'MARITALSTATUS_Single', 'last_prod_enq2_CC',
       'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL',
       'last_prod_enq2_others', 'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL',
       'first_prod_enq2_PL', 'first_prod_enq2_others']])

time_since_recent_payment VIF = 1.51
time_since_first_deliquency VIF = 10.59
time_since_recent_deliquency VIF = 7.75
num_times_delinquent VIF = 10.94
max_delinquency_level VIF = 5.45
max_recent_level_of_deliq VIF = 7.28

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\2602661993.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  vif = round(1 / (1 - rsq), 2)

num_deliq_6mts VIF = inf

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\2602661993.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  vif = round(1 / (1 - rsq), 2)

num_deliq_12mts VIF = inf

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\2602661993.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  vif = round(1 / (1 - rsq), 2)

num_deliq_6_12mts VIF = inf
max_deliq_6mts VIF = 3.03
max_deliq_12mts VIF = 4.12
num_times_30p_dpd VIF = 13.76
num_times_60p_dpd VIF = 8.82
num_std VIF = 6.15
num_std_6mts VIF = 14.06
num_std_12mts VIF = 22.61
num_sub VIF = 1.56
num_sub_6mts VIF = 2.55
num_sub_12mts VIF = 3.11
num_dbt VIF = 2.2
num_dbt_6mts VIF = 7.39
num_dbt_12mts VIF = 9.31
num_lss VIF = 2.73
num_lss_6mts VIF = 6.36
num_lss_12mts VIF = 7.95
recent_level_of_deliq VIF = 5.3
tot_enq VIF = 13.13
CC_enq VIF = 7.67
CC_enq_L6m VIF = 8.64
CC_enq_L12m VIF = 11.59
PL_enq VIF = 9.97
PL_enq_L6m VIF = 12.12
PL_enq_L12m VIF = 17.1
time_since_recent_enq VIF = 1.57
enq_L12m VIF = 25.94
enq_L6m VIF = 22.95
enq_L3m VIF = 8.22
EDUCATION VIF = 1.09
AGE VIF = 1.71
GENDER VIF = 1.06
NETMONTHLYINCOME VIF = 1.07
Time_With_Curr_Empr VIF = 1.28

C:\Users\DELL\AppData\Local\Temp\ipykernel_76996\2602661993.py:15: RuntimeWarning: divide by zero encountered in scalar divide
  vif = round(1 / (1 - rsq), 2)

pct_of_active_TLs_ever VIF = inf
pct_opened_TLs_L6m_of_L12m VIF = 5.13
pct_currentBal_all_TL VIF = 1.0

KeyboardInterrupt:

In [ ]:
vif_cal(Z = df[['time_since_recent_payment', 'num_times_delinquent',
       'max_delinquency_level', 'num_deliq_6mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_std',
       'num_std_6mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_lss',
       'num_lss_6mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'PL_enq_L6m', 'time_since_recent_enq',
       'enq_L3m', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'max_unsec_exposure_inPct', 'HL_Flag', 'GL_Flag', 'Credit_Score',
        'Total_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M',
       'pct_tl_closed_L6M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt',
       'MARITALSTATUS_Single', 'last_prod_enq2_CC',
       'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL',
        'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL',
       'first_prod_enq2_PL']])

time_since_recent_payment VIF = 1.45
num_times_delinquent VIF = 5.48
max_delinquency_level VIF = 3.51
num_deliq_6mts VIF = 2.03
max_deliq_6mts VIF = 2.84
max_deliq_12mts VIF = 2.98
num_times_30p_dpd VIF = 5.01
num_std VIF = 3.65
num_std_6mts VIF = 3.31
num_sub VIF = 1.55
num_sub_6mts VIF = 2.54
num_sub_12mts VIF = 3.1
num_dbt VIF = 1.69
num_dbt_6mts VIF = 1.64
num_lss VIF = 2.18
num_lss_6mts VIF = 2.17
recent_level_of_deliq VIF = 2.73
tot_enq VIF = 3.92
CC_enq VIF = 3.53
CC_enq_L6m VIF = 3.75
PL_enq_L6m VIF = 2.65
time_since_recent_enq VIF = 1.32
enq_L3m VIF = 3.5
EDUCATION VIF = 1.08
AGE VIF = 1.67
GENDER VIF = 1.05
NETMONTHLYINCOME VIF = 1.07
Time_With_Curr_Empr VIF = 1.28
pct_of_active_TLs_ever VIF = 2.82
pct_opened_TLs_L6m_of_L12m VIF = 1.95
pct_currentBal_all_TL VIF = 1.0
CC_Flag VIF = 1.63
PL_Flag VIF = 1.36
pct_PL_enq_L6m_of_L12m VIF = 2.2
pct_CC_enq_L6m_of_L12m VIF = 2.48
max_unsec_exposure_inPct VIF = 1.0
HL_Flag VIF = 1.5
GL_Flag VIF = 1.37
Credit_Score VIF = 3.2
Total_TL VIF = 2.59
Total_TL_opened_L6M VIF = 3.4
Tot_TL_closed_L6M VIF = 2.58
pct_tl_closed_L6M VIF = 3.04
pct_tl_open_L12M VIF = 1.96
pct_tl_closed_L12M VIF = 3.02
Tot_Missed_Pmnt VIF = 1.78
MARITALSTATUS_Single VIF = 1.38
last_prod_enq2_CC VIF = 1.54
last_prod_enq2_ConsumerLoan VIF = 1.64
last_prod_enq2_HL VIF = 1.22
last_prod_enq2_PL VIF = 1.73
first_prod_enq2_CC VIF = 1.41
first_prod_enq2_ConsumerLoan VIF = 1.32
first_prod_enq2_HL VIF = 1.36
first_prod_enq2_PL VIF = 1.26

In [ ]:
df1 = df[['time_since_recent_payment', 'num_times_delinquent',
       'max_delinquency_level', 'num_deliq_6mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_std',
       'num_std_6mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_lss',
       'num_lss_6mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'PL_enq_L6m', 'time_since_recent_enq',
       'enq_L3m', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag',
       'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m',
       'max_unsec_exposure_inPct', 'HL_Flag', 'GL_Flag', 'Credit_Score',
        'Total_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M',
       'pct_tl_closed_L6M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt',
       'MARITALSTATUS_Single', 'last_prod_enq2_CC',
       'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL',
        'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL',
       'first_prod_enq2_PL']]

In [ ]:
df1.columns

Index(['time_since_recent_payment', 'num_times_delinquent',
       'max_delinquency_level', 'num_deliq_6mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_std', 'num_std_6mts',
       'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_6mts',
       'num_lss', 'num_lss_6mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq',
       'CC_enq_L6m', 'PL_enq_L6m', 'time_since_recent_enq', 'enq_L3m',
       'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr',
       'pct_of_active_TLs_ever', 'pct_opened_TLs_L6m_of_L12m',
       'pct_currentBal_all_TL', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'Credit_Score', 'Total_TL', 'Total_TL_opened_L6M',
       'Tot_TL_closed_L6M', 'pct_tl_closed_L6M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'MARITALSTATUS_Single',
       'last_prod_enq2_CC', 'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL',
       'last_prod_enq2_PL', 'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL',
       'first_prod_enq2_PL'],
      dtype='str')

In [ ]:
y

0        0
1        0
2        0
3        0
4        0
        ..
51331    1
51332    0
51333    1
51334    0
51335    0
Name: Approved_Flag, Length: 51336, dtype: int64

In [ ]:
# Categorizing the y variable
# 0 - low Risk
# 1 - High Risk

In [ ]:
y.value_counts()

Approved_Flag
0    38002
1    13334
Name: count, dtype: int64

In [ ]:
X = df1

In [ ]:
m1 = RandomForestRegressor()

In [ ]:
rfe = RFE(estimator = m1, n_features_to_select = 20)

In [ ]:
m2 = rfe.fit(X,y)

In [ ]:
pd.DataFrame(data ={'Feature': X.columns, 'Ranking': m2.ranking_}).sort_values(by = 'Ranking',ascending = True)

                         Feature  Ranking
0      time_since_recent_payment        1
7                        num_std        1
8                   num_std_6mts        1
23                     EDUCATION        1
21         time_since_recent_enq        1
27           Time_With_Curr_Empr        1
28        pct_of_active_TLs_ever        1
30         pct_currentBal_all_TL        1
24                           AGE        1
26              NETMONTHLYINCOME        1
22                       enq_L3m        1
16         recent_level_of_deliq        1
17                       tot_enq        1
18                        CC_enq        1
39                      Total_TL        1
35      max_unsec_exposure_inPct        1
43              pct_tl_open_L12M        1
38                  Credit_Score        1
44            pct_tl_closed_L12M        1
42             pct_tl_closed_L6M        1
2          max_delinquency_level        2
29    pct_opened_TLs_L6m_of_L12m        3
1           num_times_delinquent        4
45               Tot_Missed_Pmnt        5
41             Tot_TL_closed_L6M        6
40           Total_TL_opened_L6M        7
4                 max_deliq_6mts        8
25                        GENDER        9
36                       HL_Flag       10
48   last_prod_enq2_ConsumerLoan       11
52  first_prod_enq2_ConsumerLoan       12
32                       PL_Flag       13
46          MARITALSTATUS_Single       14
49             last_prod_enq2_HL       15
20                    PL_enq_L6m       16
3                 num_deliq_6mts       17
5                max_deliq_12mts       18
6              num_times_30p_dpd       19
34        pct_CC_enq_L6m_of_L12m       20
50             last_prod_enq2_PL       21
31                       CC_Flag       22
54            first_prod_enq2_PL       23
37                       GL_Flag       24
47             last_prod_enq2_CC       25
53            first_prod_enq2_HL       26
33        pct_PL_enq_L6m_of_L12m       27
51            first_prod_enq2_CC       28
19                    CC_enq_L6m       29
9                        num_sub       30
12                       num_dbt       31
11                 num_sub_12mts       32
10                  num_sub_6mts       33
15                  num_lss_6mts       34
14                       num_lss       35
13                  num_dbt_6mts       36

In [ ]:
X = df[['time_since_recent_payment','num_std','num_std_6mts','EDUCATION','time_since_recent_enq','pct_of_active_TLs_ever','pct_opened_TLs_L6m_of_L12m',
       'pct_currentBal_all_TL','AGE','NETMONTHLYINCOME','Time_With_Curr_Empr','tot_enq','enq_L3m',
       'Total_TL','max_unsec_exposure_inPct','pct_tl_open_L12M','Credit_Score','pct_tl_closed_L12M','pct_tl_closed_L6M']]

In [ ]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [ ]:
m2 = LogisticRegression(max_iter = 10000, class_weight = 'balanced', random_state = 42,n_jobs = -1)
m2 = m2.fit(Xtrain,ytrain)

c:\Users\DELL\OneDrive\Desktop\Loan Risk Analysis\zubair9141@gmail.com\Python Analysis & Web App\loan_app\credit_env1\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
c:\Users\DELL\OneDrive\Desktop\Loan Risk Analysis\zubair9141@gmail.com\Python Analysis & Web App\loan_app\credit_env1\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
train_pred = m2.predict(Xtrain)
test_pred = m2.predict(Xtest)

In [ ]:
print(metrics.confusion_matrix(ytrain,train_pred))

[[24976  5512]
 [ 2781  7799]]

In [ ]:
print(metrics.classification_report(ytrain,train_pred))

              precision    recall  f1-score   support

           0       0.90      0.82      0.86     30488
           1       0.59      0.74      0.65     10580

    accuracy                           0.80     41068
   macro avg       0.74      0.78      0.76     41068
weighted avg       0.82      0.80      0.80     41068

In [ ]:
accuracy = metrics.accuracy_score(ytrain, train_pred)
print("Accuracy:", accuracy)

Accuracy: 0.798066621213597

In [ ]:
print(metrics.confusion_matrix(ytest,test_pred))

[[6181 1333]
 [ 741 2013]]

In [ ]:
print(metrics.classification_report(ytest,test_pred))

              precision    recall  f1-score   support

           0       0.89      0.82      0.86      7514
           1       0.60      0.73      0.66      2754

    accuracy                           0.80     10268
   macro avg       0.75      0.78      0.76     10268
weighted avg       0.81      0.80      0.80     10268

In [ ]:
accuracy = metrics.accuracy_score(ytest, test_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7980132450331126

In [ ]:
m3 = RandomForestClassifier()
m3 = m3.fit(Xtrain,ytrain)

In [ ]:
Xtrain.duplicated().sum()

np.int64(0)

In [ ]:
train_pred = m3.predict(Xtrain)
test_pred = m3.predict(Xtest)

In [ ]:
print(metrics.confusion_matrix(ytrain,train_pred))

[[30488     0]
 [    0 10580]]

In [ ]:
print(metrics.classification_report(ytrain,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     30488
           1       1.00      1.00      1.00     10580

    accuracy                           1.00     41068
   macro avg       1.00      1.00      1.00     41068
weighted avg       1.00      1.00      1.00     41068

In [ ]:
accuracy = metrics.accuracy_score(ytrain, train_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
print(metrics.confusion_matrix(ytest,test_pred))

[[7489   25]
 [  73 2681]]

In [ ]:
print(metrics.classification_report(ytest,test_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      7514
           1       0.99      0.97      0.98      2754

    accuracy                           0.99     10268
   macro avg       0.99      0.99      0.99     10268
weighted avg       0.99      0.99      0.99     10268

In [ ]:
accuracy = metrics.accuracy_score(ytest, test_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9904557849629918

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(m3, X, y, cv=5, scoring='f1')
print(scores)
print(scores.mean())

[0.97185813 0.97145062 0.97265023 0.98223062 0.98068788]
0.975775497145651

In [ ]:
importance = pd.Series(m3.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

Credit_Score                  0.758849
enq_L3m                       0.085531
time_since_recent_enq         0.041913
tot_enq                       0.025167
num_std                       0.015505
num_std_6mts                  0.011790
pct_tl_open_L12M              0.009160
time_since_recent_payment     0.007147
AGE                           0.006898
Time_With_Curr_Empr           0.005705
pct_currentBal_all_TL         0.005166
NETMONTHLYINCOME              0.004844
max_unsec_exposure_inPct      0.004553
Total_TL                      0.004325
pct_of_active_TLs_ever        0.004142
pct_opened_TLs_L6m_of_L12m    0.002897
pct_tl_closed_L12M            0.002450
EDUCATION                     0.002267
pct_tl_closed_L6M             0.001690
dtype: float64

In [ ]:
#import joblib

In [157]:
print(Xtrain.columns)

Index(['time_since_recent_payment', 'num_std', 'num_std_6mts', 'EDUCATION',
       'time_since_recent_enq', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'AGE',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'tot_enq', 'enq_L3m',
       'Total_TL', 'max_unsec_exposure_inPct', 'pct_tl_open_L12M',
       'Credit_Score', 'pct_tl_closed_L12M', 'pct_tl_closed_L6M'],
      dtype='str')

In [ ]:
from joblib import dump

dump(m3, "RFC.pkl")
dump(Xtrain.columns.tolist(), "features.pkl")

['features.pkl']

In [167]:
import pandas as pd

# Load original datasets
internal = pd.read_csv("Internal_Bank_Cleaned.csv")
external = pd.read_csv("External_CIBIL_Cleaned.csv")

# Merge
df = external.merge(internal, on="PROSPECTID", how="left")

# Keep only dashboard columns
dashboard_cols = [
    "GENDER",
    "AGE",
    "NETMONTHLYINCOME",
    "Credit_Score",
    "num_times_delinquent"
]

dashboard_df = df[dashboard_cols]

# Convert numeric columns
numeric_cols = [
    "AGE",
    "NETMONTHLYINCOME",
    "Credit_Score",
    "num_times_delinquent"
]

for col in numeric_cols:
    dashboard_df[col] = pd.to_numeric(
        dashboard_df[col],
        errors="coerce"
    )

# Remove invalid rows
dashboard_df = dashboard_df.dropna()

# OPTIONAL: sample only if dataset is huge
dashboard_df = dashboard_df.sample(
    min(len(dashboard_df), 51336),
    random_state=42
)

# Save
dashboard_df.to_csv(
    "dashboard_data.csv",
    index=False
)

print(dashboard_df.shape)
print(dashboard_df.head())

(51290, 5)
      GENDER  AGE  NETMONTHLYINCOME  Credit_Score  num_times_delinquent
49773      F   47           42000.0           672                     0
45586      M   58           40000.0           681                     0
15680      M   23           16000.0           673                     2
40598      M   22           25000.0           633                     2
49471      M   34           36500.0           683                     7

In [162]:
df1 = pd.read_csv("dashboard_data.csv")
print(df1.columns.tolist())

['GENDER', 'AGE', 'NETMONTHLYINCOME', 'Credit_Score', 'num_times_delinquent']

In [166]:
df.shape

(51336, 96)

In [ ]:
# Load datasets
internal = pd.read_csv("Internal_Bank_Cleaned.csv")
external = pd.read_csv("External_CIBIL_Cleaned.csv")

# Merge
df = external.merge(internal, on="PROSPECTID", how="left")

# Keep ONLY dashboard columns
dashboard_cols = [
    "GENDER",
    "AGE",
    "NETMONTHLYINCOME",
    "Credit_Score",
    "num_times_delinquent"
]

dashboard_df = df[dashboard_cols]

# Convert numeric columns safely
numeric_cols = [
    "AGE",
    "NETMONTHLYINCOME",
    "Credit_Score",
    "num_times_delinquent"
]

for col in numeric_cols:
    dashboard_df[col] = pd.to_numeric(
        dashboard_df[col],
        errors="coerce"
    )

# Remove invalid rows
dashboard_df = dashboard_df.dropna()

# Save final dashboard dataset
dashboard_df.to_csv(
    "dashboard_data.csv",
    index=False
)

print(dashboard_df.shape)
print(dashboard_df.head())

(51290, 5)
  GENDER  AGE  NETMONTHLYINCOME  Credit_Score  num_times_delinquent
0      M   48           51000.0           696                    11
1      F   23           19000.0           685                     0
2      M   40              18.0           693                     9
3      M   34           10000.0           673                     0
4      M   48           15000.0           753                     0